spring:
  config:
    import:
      - classpath:/config/application-mysql.yml
      - classpath:/config/application-redis.yml
#    import: [classpath:/config/application-mysql.yml, classpath:/config/application-redis.yml]